[project]
name = "usbip-ice"
version = "0.1"
dependencies = [
    "Flask",
    "pexpect",
    "psycopg[binary]",
    "pyudev",
    "requests",
    "schedule",
    "waitress"
]

[project.scripts]
worker = "worker:worker.main"
control = "control:server.main"
usbipconnect = "client:cli.main"
heartbeat = "control:heartbeat.main"

[tool.setuptools]
py-modules = ["client", "worker", "control", "utils"]

[tools.setuptools.find]
where = ["worker/firmware/build"]

[tool.setuptools.package-data]
data = ["worker/firmware/build/default_firmware.uf2"]