name: Docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push arm
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: usbipiceproject/usbipice-worker:arm
          file: deploy/Dockerfile
          platforms: linux/arm64
          cache-from: type=registry,ref=usbipiceproject/usbipice-worker:arm
          cache-to: type=inline,mode=max

      -
        name: Build and push amd
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: usbipiceproject/usbipice-worker:amd
          file: deploy/Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=usbipiceproject/usbipice-worker:amd
          cache-to: type=inline,mode=max

